name: Final Combined Workflow

on:
  push:

jobs:
  full-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 24f1000952@ds.study.iitm.ac.in
        run: echo Hello

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-5010c89
          restore-keys: |
            cache-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: prime-cache-5010c89
        run: echo "Cache hit? ${{ steps.cache.outputs.cache-hit }}"
